spring:
  application:
    name: openai-advanced
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
    vectorstore:
      qdrant:
        initialize-schema: true
        host: localhost
        port: 6334
        collection-name: myai
  docker:
    compose:
      stop:
        command: down # demo purpose
logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG
